### ISSUE TITLE
not able to add notes

### ISSUE THREAD

**Issue by nagim** [GitbookIO/plugin-hints#1]
Hi,

The hint texts are not put into a `<p>` tag, so inline notes function does not work on the texts. Could you please add it?
Also, is it possible to add icons before the text?

Thanks,
Imre

**Comment by Soreine** [comment]
We fixed the icons. And the inner content is now parsed as Markdown (which yields paragraphs). There was no easy way to make it detect Asciidoc as the syntax used though... This will be much easier to do with GitBook v4.
